Working
KMA-global/HW pull request #1
Opened 2021-04-15 14:17 UTC by KMA-global

Выполнение заданий для курса Web Services Testing (3 weeks)

2021-04-20 20:43 UTC, zhidelev requested changes
Максим, посмотри комментарии и поправь 👍

2021-04-20 20:43 UTC, zhidelev commented on Task_3/source/worker_speller.py
> +    req = f"https://speller.yandex.net/services/spellservice.json/{method}"
Думаю, что адрес можно вынести в константу типа `SPELLER_URL`  в начало файла, чтобы его было проще менять если что,

2021-04-20 20:43 UTC, zhidelev commented on Task_3/source/worker_speller.py
> +    response.close()
Никогда не сталкивался. Зачем тут нужен `close()` ?

2021-04-20 20:43 UTC, zhidelev commented on Task_3/source/worker_speller.py
> +    except:
Лучше ловить определённый exception, a не все.

2021-04-20 20:43 UTC, zhidelev commented on Task_3/source/worker_speller.py
> +            парметры запроса
Параметры

2021-04-20 20:43 UTC, zhidelev commented on Task_3/source/worker_speller.py
> +def send_request(method, **options):
`**options` это `**kwargs` ? А то в parameters тоже есть options.

2021-04-20 20:43 UTC, zhidelev commented on Task_3/tests/test_service.py
> +from source.worker_speller import *
Использовать `*` при импорте - плохая практика. Лучше указывать конкретно что импортируешь или сделать так `from source.worker_speller as speller` и уже в коде использовать `speller.method()`

2021-04-20 20:43 UTC, zhidelev commented on Task_3/tests/test_service.py
> +class Test_YaSpeller:
Просто CamelCase . Без `_` .

2021-04-20 20:43 UTC, zhidelev commented on Task_3/tests/test_service.py
> +    def test_correct_text(self):
Тут можно параметризовать тест, т.к. спеллер принимает ru, uk, en , а в тесте проверяется только ru.

2021-04-20 20:43 UTC, zhidelev commented on Task_3/source/source_speller.py
> +class Source:
Может переименовать в `DataSet` ил ещё как-то? `Source` мне кажется неочевидным.

2021-04-20 20:43 UTC, zhidelev commented on Task_3/source/source_speller.py
> +class Source:
Я бы вобще назвал `source_speller.py` как `dataset.py` , в нём просто набор словарей lang, options и т.п.

2021-04-22 14:48 UTC, KMA-global commented on Task_3/source/worker_speller.py
> +    req = f"https://speller.yandex.net/services/spellservice.json/{method}"
Исправлено.

2021-04-22 14:48 UTC, KMA-global commented on Task_3/source/worker_speller.py
> +    response.close()
Неправильное использование. Исправлено на использование Session.
В прошлых проектах помогало избавиться от “Too many open files", даже без Session.

2021-04-22 14:48 UTC, KMA-global commented on Task_3/source/worker_speller.py
> +    except:
Исправлено.

2021-04-22 14:48 UTC, KMA-global commented on Task_3/source/worker_speller.py
> +            парметры запроса
Исправлено.

2021-04-22 14:48 UTC, KMA-global commented on Task_3/source/worker_speller.py
> +def send_request(method, **options):
Убрал путаницу. **options -> **kwargs

2021-04-22 14:48 UTC, KMA-global commented on Task_3/tests/test_service.py
> +from source.worker_speller import *
Исправлено.

2021-04-22 14:48 UTC, KMA-global commented on Task_3/tests/test_service.py
> +class Test_YaSpeller:
Исправлено.

2021-04-22 14:48 UTC, KMA-global commented on Task_3/tests/test_service.py
> +    def test_correct_text(self):
Тест параметризован

2021-04-22 14:49 UTC, KMA-global commented on Task_3/source/source_speller.py
> +class Source:
Исправлено.

2021-04-22 19:06 UTC, zhidelev approved these changes
Молодец, принято 👍

2021-04-22 19:06 UTC, zhidelev commented on Task_3/source/worker_speller.py
> +    result["status_code"] = code
Наверно создавать `code` излишне, можно было просто `result["status_code"] = response.status_code` . Но это не критично сейчас.

2021-04-27 11:09 UTC, merged